// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP3SmYJ_YTA2U2ysDtcU0UGkquW1Act54',
    appId: '1:826614414608:web:14841c0b461d194a0d7995',
    messagingSenderId: '826614414608',
    projectId: 'bread-road',
    authDomain: 'bread-road.firebaseapp.com',
    storageBucket: 'bread-road.firebasestorage.app',
    measurementId: 'G-0FT1GSY7P1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi207Qsh60S2wjM5o8CEKfiuUqGujUZ4c',
    appId: '1:826614414608:android:7f0d94198fd236460d7995',
    messagingSenderId: '826614414608',
    projectId: 'bread-road',
    storageBucket: 'bread-road.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9bU1ZuZOsUPMh7o9tA5gE-lqBGh2SQmk',
    appId: '1:826614414608:ios:fe078169a16ca7b90d7995',
    messagingSenderId: '826614414608',
    projectId: 'bread-road',
    storageBucket: 'bread-road.firebasestorage.app',
    iosBundleId: 'com.breadroad.name',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9bU1ZuZOsUPMh7o9tA5gE-lqBGh2SQmk',
    appId: '1:826614414608:ios:0c642cf17d32cfff0d7995',
    messagingSenderId: '826614414608',
    projectId: 'bread-road',
    storageBucket: 'bread-road.firebasestorage.app',
    iosBundleId: 'com.example.breadRoad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP3SmYJ_YTA2U2ysDtcU0UGkquW1Act54',
    appId: '1:826614414608:web:257033604b0efac00d7995',
    messagingSenderId: '826614414608',
    projectId: 'bread-road',
    authDomain: 'bread-road.firebaseapp.com',
    storageBucket: 'bread-road.firebasestorage.app',
    measurementId: 'G-6X7KSBSP4W',
  );
}
